---
- name: Install python3
  become_user: "{{ ai_super_user }}"
  ansible.builtin.package:
    name: python3
    state: present
- name: Install python3-pip
  become_user: "{{ ai_super_user }}"
  ansible.builtin.package:
    name: python3-pip
    state: present

- name: Upgrade Pip from Pip
  ansible.builtin.command:
    cmd: pip install -U pip
 
- name: Install python3-venv
  become_user: "{{ ai_super_user }}"
  ansible.builtin.package:
    name: python3-venv
    state: present
- name: Run pip install docker-compose
  ansible.builtin.pip:
    name: docker-compose
    state: present
- name: Run pip install docker[tls]
  ansible.builtin.pip:
    name: docker[tls]
    state: present
