---
- name: Clone llm-on-prem
  become_user: "{{ ai_user }}"
  ansible.builtin.git:
    repo: "{{ llm_on_prem_url }}"
    dest: "{{ llm_on_prem_home }}"
    version: "{{ llm_on_prem_version }}"
    force: true
    depth: 1

- name: Python Setup for Workers
  ansible.builtin.include_tasks: ai-worker-python-setup.yml

- name: Setup env templates
  ansible.builtin.include_tasks: setup-env-templates.yml


- name: Install Containers Portion
  ansible.builtin.include_tasks: llm-container-build.yml

- name: Setup Python venv
  ansible.builtin.include_tasks: ai-worker-python-venv.yml

- name: Huggingface download
  ansible.builtin.include_tasks: huggingface-model-setup.yml
