---
- name: Set up docker
  ansible.builtin.include_tasks: setup-docker.yml

- name: Python Setup for Workers
  ansible.builtin.include_tasks: ai-worker-python-setup.yml

- name: Setup env templates
  ansible.builtin.include_tasks: setup-env-templates.yml


- name: Install Containers Portion
  ansible.builtin.include_tasks: llm-container-build.yml

- name: Setup Python venv
  ansible.builtin.include_tasks: ai-worker-python-venv.yml

- name: Huggingface download
  ansible.builtin.include_tasks: huggingface-model-setup.yml
