---
- name: Set up funky script to download models
  become_user: "{{ ai_user }}"
  ansible.builtin.template:
    src: "{{ llm_on_prem_template_dir }}/llm-on-prem/download-model.sh.j2"
    dest: "{{ llm_on_prem_home_docker_compose_home }}/download-model.sh"
    owner: "{{ ai_user }}"
    group: "{{ ai_group }}"
    mode: "0755"
- name: Set up LLM on prem .env
  become_user: "{{ ai_user }}"
  ansible.builtin.template:
    src: "{{ llm_on_prem_template_dir }}/llm-on-prem/dotenv.j2"
    dest: "{{ llm_on_prem_home_docker_compose_home }}/.env"
    owner: "{{ ai_user }}"
    group: "{{ ai_group }}"
    mode: "0644"
- name: Set up LLM on prem .env.mac
  become_user: "{{ ai_user }}"
  ansible.builtin.template:
    src: "{{ llm_on_prem_template_dir }}/llm-on-prem/dotenv.mac.j2"
    dest: "{{ llm_on_prem_home_docker_compose_home }}/.env.mac"
    owner: "{{ ai_user }}"
    group: "{{ ai_group }}"
    mode: "0644"
